services:
  cvuser:
    build:
      context: ./cvuser
    user: "node"
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - './../cv-user:/home/node/app'
    ports:
    - "8080:8080"
    - "8000:8000"
    command: sh -c "npm install && tail -F /dev/null"
networks:
  net-test: